services:
  fhir:
    build:
      context: ./hub-prime/
      dockerfile: Dockerfile
      args:
        REPO_URL: ${REPO_URL}
        TAG: ${TAG}
        DATE: ${DATE}
        SPRING_PROFILES_ACTIVE: sandbox
        sandbox_TECHBD_UDI_DS_PRIME_JDBC_URL: ${sandbox_TECHBD_UDI_DS_PRIME_JDBC_URL}
        sandbox_TECHBD_UDI_DS_PRIME_JDBC_USERNAME: ${sandbox_TECHBD_UDI_DS_PRIME_JDBC_USERNAME}
        sandbox_TECHBD_UDI_DS_PRIME_JDBC_PASSWORD: ${sandbox_TECHBD_UDI_DS_PRIME_JDBC_PASSWORD}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_0_TENANTID: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_0_TENANTID}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_0_SERVER: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_0_SERVER}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_0_PORT: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_0_PORT}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_0_USERNAME: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_0_USERNAME}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_0_PASSWORD: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_0_PASSWORD}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_1_TENANTID: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_1_TENANTID}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_1_SERVER: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_1_SERVER}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_1_PORT: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_1_PORT}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_1_USERNAME: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_1_USERNAME}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_1_PASSWORD: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_1_PASSWORD}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_2_TENANTID: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_2_TENANTID}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_2_SERVER: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_2_SERVER}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_2_PORT: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_2_PORT}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_2_USERNAME: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_2_USERNAME}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_2_PASSWORD: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_2_PASSWORD}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_3_TENANTID: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_3_TENANTID}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_3_SERVER: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_3_SERVER}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_3_PORT: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_3_PORT}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_3_USERNAME: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_3_USERNAME}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_3_PASSWORD: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_3_PASSWORD}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_4_TENANTID: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_4_TENANTID}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_4_SERVER: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_4_SERVER}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_4_PORT: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_4_PORT}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_4_USERNAME: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_4_USERNAME}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_4_PASSWORD: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_4_PASSWORD}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_5_TENANTID: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_5_TENANTID}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_5_SERVER: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_5_SERVER}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_5_PORT: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_5_PORT}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_5_USERNAME: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_5_USERNAME}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_5_PASSWORD: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_5_PASSWORD}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_6_TENANTID: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_6_TENANTID}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_6_SERVER: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_6_SERVER}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_6_PORT: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_6_PORT}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_6_USERNAME: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_6_USERNAME}
        ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_6_PASSWORD: ${ORG_TECHBD_ORCHESTRATE_SFTP_ACCOUNT_ORCHCTLTS_6_PASSWORD}
        SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_ID: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_ID}
        SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET}
        ORG_TECHBD_SERVICE_HTTP_GITHUB_AUTHZ_USERS_YAML_URL: ${ORG_TECHBD_SERVICE_HTTP_GITHUB_AUTHZ_USERS_YAML_URL}
        ORG_TECHBD_SERVICE_HTTP_GITHUB_API_AUTHN_TOKEN: ${ORG_TECHBD_SERVICE_HTTP_GITHUB_API_AUTHN_TOKEN}
    ports:
      - "8080:8080"
